import { useCallback, useEffect, useRef, useState, type ReactElement } from 'react'
import { BookOpen, ChevronDown, FilePlus2, FolderPlus, Menu, MoreHorizontal, PanelLeftClose, Search, Trash2 } from 'lucide-react'
import { Group, Panel, Separator } from 'react-resizable-panels'
import type { Job, NotebookTree, PageWorkspace, SearchResult, TrashRecord } from '../../shared/domain'
import { Button, DropdownMenu, IconTip, Input, Modal } from './components/ui'
import { PageWorkspace as EditorWorkspace } from './features/editor/PageWorkspace'
import { SourceWorkspace } from './features/sources/SourceWorkspace'

const errorMessage = (error: unknown): string => error instanceof Error ? error.message : 'The requested change could not be saved.'
type Utility = 'settings' | 'diagnostics' | 'export' | 'jobs' | 'trash' | null

export function App(): ReactElement {
  const [notebooks, setNotebooks] = useState<NotebookTree[]>([]); const [workspace, setWorkspace] = useState<PageWorkspace | null>(null); const [selectedPageId, setSelectedPageId] = useState<string | null>(null); const [activeNoteId, setActiveNoteId] = useState<string | null>(null)
  const [mode, setMode] = useState<'write' | 'research'>('write'); const [sidebarCollapsed, setSidebarCollapsed] = useState(false); const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [paletteOpen, setPaletteOpen] = useState(false); const [utility, setUtility] = useState<Utility>(null); const [trash, setTrash] = useState<TrashRecord[]>([]); const [error, setError] = useState<string | null>(null)
  const searchInput = useRef<HTMLInputElement>(null)
  const refreshTree = useCallback(async () => setNotebooks(await window.researchNotebook.notebooks.list()), [])
  const refreshTrash = useCallback(async () => setTrash(await window.researchNotebook.trash.list()), [])
  const openPage = useCallback(async (pageId: string, cursor?: string) => { setError(null); setSelectedPageId(pageId); setActiveNoteId(null); setWorkspace(await window.researchNotebook.pages.getWorkspace({ pageId, cursor })) }, [])
  const reloadWorkspace = useCallback(async () => { if (selectedPageId) { setWorkspace(await window.researchNotebook.pages.getWorkspace({ pageId: selectedPageId })); setActiveNoteId(null) } }, [selectedPageId])
  const trashChanged = useCallback(async () => { await Promise.all([refreshTree(), refreshTrash()]); if (selectedPageId) try { await reloadWorkspace() } catch { setWorkspace(null); setSelectedPageId(null) } }, [refreshTree, refreshTrash, reloadWorkspace, selectedPageId])
  useEffect(() => { void refreshTree().catch((error: unknown) => setError(errorMessage(error))) }, [refreshTree])
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); setPaletteOpen(true); requestAnimationFrame(() => searchInput.current?.focus()) } if ((event.metaKey || event.ctrlKey) && event.shiftKey && event.key.toLowerCase() === 'n' && workspace) { event.preventDefault(); void window.researchNotebook.notes.create({ pageId: workspace.id, title: 'Untitled note' }).then(reloadWorkspace).catch((error: unknown) => setError(errorMessage(error))) } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler) }, [workspace, reloadWorkspace])
  const search = async (value = query) => { try { setResults(value.trim() ? await window.researchNotebook.search({ query: value }) : []) } catch (error) { setError(errorMessage(error)) } }
  const selectResult = async (result: SearchResult) => { try { if (result.pageId) await openPage(result.pageId, result.notePosition && result.notePosition > 0 ? String(result.notePosition - 1) : undefined); else if (result.notebookId) { const notebook = notebooks.find(({ id }) => id === result.notebookId); if (notebook?.pages[0]) await openPage(notebook.pages[0].id) }; setPaletteOpen(false) } catch (error) { setError(errorMessage(error)) } }
  const createNotebook = async () => { try { const notebook = await window.researchNotebook.notebooks.create({ title: 'Untitled notebook' }); const page = await window.researchNotebook.pages.create({ notebookId: notebook.id, title: 'Untitled page' }); await refreshTree(); await openPage(page.id) } catch (error) { setError(errorMessage(error)) } }
  const notebookId = selectedPageId ? notebooks.find((notebook) => notebook.pages.some(({ id }) => id === selectedPageId))?.id ?? null : null
  const openUtility = async (kind: Utility) => { if (kind === 'trash') try { await refreshTrash() } catch (error) { setError(errorMessage(error)); return }; setUtility(kind) }
  const editor = workspace && <EditorWorkspace workspace={workspace} notebookId={notebookId} mode={mode} reloadWorkspace={reloadWorkspace} loadMore={async () => { if (!workspace.nextCursor) return; const next = await window.researchNotebook.pages.getWorkspace({ pageId: workspace.id, cursor: workspace.nextCursor }); setWorkspace({ ...next, notes: [...workspace.notes, ...next.notes] }) }} activeNoteId={activeNoteId} setActiveNoteId={setActiveNoteId} onError={(error) => setError(errorMessage(error))} onChanged={refreshTree} onTrashed={trashChanged} onViewSource={() => setMode('research')} onUtilities={openUtility} />
  return <main className={`app-shell ${mode}-mode ${sidebarCollapsed ? 'sidebar-collapsed' : ''}`}>
    {!sidebarCollapsed && <NotebookSidebar notebooks={notebooks} selectedPageId={selectedPageId} onOpenPage={openPage} onRefresh={refreshTree} onError={(error) => setError(errorMessage(error))} onTrashed={trashChanged} onNewNotebook={createNotebook} />}
    <section className="application-main"><header className="app-toolbar"><IconTip label="Collapse sidebar"><Button variant="icon" aria-label="Collapse notebook sidebar" onClick={() => setSidebarCollapsed(true)}><PanelLeftClose size={18} /></Button></IconTip><button className="command-search" onClick={() => setPaletteOpen(true)}><Search size={17} /><span>Search notes, sources, or ask…</span><kbd>⌘ K</kbd></button><div className="workspace-switcher" aria-label="Workspace mode"><button className={mode === 'research' ? 'selected' : ''} aria-pressed={mode === 'research'} onClick={() => setMode('research')}><BookOpen size={15} /> Research</button><button className={mode === 'write' ? 'selected' : ''} aria-pressed={mode === 'write'} onClick={() => setMode('write')}>Write</button></div><AppMenu openUtility={openUtility} reloadWorkspace={reloadWorkspace} onError={(error) => setError(errorMessage(error))} /></header>
      {error && <div className="error" role="alert">{error}<Button variant="ghost" size="sm" onClick={() => setError(null)}>Dismiss</Button></div>}
      {workspace ? mode === 'research' ? <Group className="research-layout" orientation="horizontal"><Panel id="source" defaultSize="42" minSize="30" maxSize="55"><section className="source-pane"><SourceWorkspace notebookId={notebookId} workspace={workspace} activeNoteId={activeNoteId} onSaved={reloadWorkspace} onError={(error) => setError(errorMessage(error))} onUtilities={openUtility} /></section></Panel><Separator className="pane-resize" /><Panel id="editor" minSize="45"><section className="editor-pane">{editor}</section></Panel></Group> : <div className="write-layout">{editor}</div> : <Empty onNewNotebook={createNotebook} />}</section>
    {sidebarCollapsed && <Button className="sidebar-reopen" variant="icon" aria-label="Expand notebook sidebar" onClick={() => setSidebarCollapsed(false)}><Menu size={18} /></Button>}
    <CommandPalette open={paletteOpen} onOpenChange={setPaletteOpen} query={query} setQuery={setQuery} results={results} onSearch={search} onSelect={selectResult} inputRef={searchInput} />
    <UtilityDialogs utility={utility} onOpenChange={(open) => !open && setUtility(null)} notebookId={notebookId} workspace={workspace} activeNoteId={activeNoteId} trash={trash} onChanged={trashChanged} onError={(error) => setError(errorMessage(error))} />
  </main>
}

function AppMenu({ openUtility, reloadWorkspace, onError }: { openUtility: (kind: Utility) => Promise<void>; reloadWorkspace: () => Promise<void>; onError: (error: unknown) => void }): ReactElement { return <DropdownMenu.Root><DropdownMenu.Trigger asChild><Button variant="icon" aria-label="Application menu"><MoreHorizontal size={18} /></Button></DropdownMenu.Trigger><DropdownMenu.Portal><DropdownMenu.Content className="menu-content" align="end"><DropdownMenu.Item className="menu-item" onSelect={() => void window.researchNotebook.imports.start().then(reloadWorkspace).catch(onError)}>Import backup</DropdownMenu.Item><DropdownMenu.Item className="menu-item" onSelect={() => void window.researchNotebook.backups.start().catch(onError)}>Back up library</DropdownMenu.Item><DropdownMenu.Separator className="menu-separator" />{(['jobs', 'diagnostics', 'settings', 'trash'] as const).map((kind) => <DropdownMenu.Item key={kind} className="menu-item" onSelect={() => void openUtility(kind)}>{kind}</DropdownMenu.Item>)}</DropdownMenu.Content></DropdownMenu.Portal></DropdownMenu.Root> }

function NotebookSidebar({ notebooks, selectedPageId, onOpenPage, onRefresh, onError, onTrashed, onNewNotebook }: { notebooks: NotebookTree[]; selectedPageId: string | null; onOpenPage: (id: string) => Promise<void>; onRefresh: () => Promise<void>; onError: (error: unknown) => void; onTrashed: () => Promise<void>; onNewNotebook: () => Promise<void> }): ReactElement { const [newPage, setNewPage] = useState(''); const createPage = async (notebookId: string) => { try { const page = await window.researchNotebook.pages.create({ notebookId, title: newPage.trim() || 'Untitled page' }); setNewPage(''); await onRefresh(); await onOpenPage(page.id) } catch (error) { onError(error) } }; return <aside className="sidebar" aria-label="Notebooks"><div className="product-name"><BookOpen size={20} />Research Notebook</div><div className="sidebar-search"><Search size={16} /><input aria-label="Filter notebook pages" placeholder="Search notes…" /><kbd>⌘ K</kbd></div><div className="sidebar-label">MY NOTEBOOK <ChevronDown size={14} /></div><nav>{notebooks.map((notebook) => <section className="notebook-tree" key={notebook.id}><div className="tree-title"><FolderPlus size={14} /><input aria-label="Notebook title" defaultValue={notebook.title} onBlur={(event) => { if (event.currentTarget.value.trim() !== notebook.title) void window.researchNotebook.notebooks.update({ notebookId: notebook.id, title: event.currentTarget.value }).then(onRefresh).catch(onError) }} /><button aria-label={`Move ${notebook.title} to trash`} onClick={() => void window.researchNotebook.trash.move({ entityType: 'notebook', id: notebook.id }).then(onTrashed).catch(onError)}><Trash2 size={13} /></button></div>{notebook.pages.map((page) => <button key={page.id} className={`page-link ${page.id === selectedPageId ? 'active' : ''}`} aria-current={page.id === selectedPageId ? 'page' : undefined} onClick={() => void onOpenPage(page.id).catch(onError)}>{page.title}</button>)}<div className="new-page"><input aria-label={`New page for ${notebook.title}`} value={newPage} onChange={(event) => setNewPage(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void createPage(notebook.id) }} placeholder="New page" /><button aria-label="Create page" onClick={() => void createPage(notebook.id)}><FilePlus2 size={15} /></button></div></section>)}</nav><Button className="new-notebook" variant="secondary" onClick={() => void onNewNotebook()}><FolderPlus size={16} /> New notebook</Button></aside> }

function CommandPalette({ open, onOpenChange, query, setQuery, results, onSearch, onSelect, inputRef }: { open: boolean; onOpenChange: (open: boolean) => void; query: string; setQuery: (query: string) => void; results: SearchResult[]; onSearch: (query?: string) => Promise<void>; onSelect: (result: SearchResult) => Promise<void>; inputRef: React.RefObject<HTMLInputElement | null> }): ReactElement { return <Modal title="Search your notebook" open={open} onOpenChange={onOpenChange}><div className="command-palette"><div className="palette-input"><Search size={18} /><Input ref={inputRef} value={query} onChange={(event) => { setQuery(event.target.value); void onSearch(event.target.value) }} placeholder="Search notes, sources, or ask…" /></div>{results.length ? <div className="search-results">{results.map((result) => <button key={`${result.entityType}-${result.entityId}`} onClick={() => void onSelect(result)}><strong>{result.title}</strong><small>{result.entityType} · {result.excerpt || 'Match'}</small></button>)}</div> : <p className="palette-empty">Start typing to search pages, notes, and blocks.</p>}</div></Modal> }

function UtilityDialogs({ utility, onOpenChange, notebookId, workspace, activeNoteId, trash, onChanged, onError }: { utility: Utility; onOpenChange: (open: boolean) => void; notebookId: string | null; workspace: PageWorkspace | null; activeNoteId: string | null; trash: TrashRecord[]; onChanged: () => Promise<void>; onError: (error: unknown) => void }): ReactElement { return <>{utility === 'settings' && <SettingsDialog onOpenChange={onOpenChange} onError={onError} />}{utility === 'jobs' && <JobsDialog onOpenChange={onOpenChange} onError={onError} />}{utility === 'diagnostics' && <DiagnosticsDialog notebookId={notebookId} onOpenChange={onOpenChange} onError={onError} />}{utility === 'export' && <ExportDialog notebookId={notebookId} workspace={workspace} activeNoteId={activeNoteId} onOpenChange={onOpenChange} onError={onError} />}{utility === 'trash' && <TrashDialog records={trash} onOpenChange={onOpenChange} onChanged={onChanged} onError={onError} />}</> }
function SettingsDialog({ onOpenChange, onError }: { onOpenChange: (open: boolean) => void; onError: (error: unknown) => void }): ReactElement { const [key, setKey] = useState(''); const [configured, setConfigured] = useState(false); useEffect(() => { void window.researchNotebook.settings.transcription().then((value) => setConfigured(value.openRouterConfigured)).catch(onError) }, [onError]); return <Modal title="Settings" open onOpenChange={onOpenChange}><p className="dialog-copy">OpenRouter {configured ? 'is configured.' : 'is not configured.'}</p><label className="field-label">OpenRouter API key<Input type="password" value={key} onChange={(event) => setKey(event.target.value)} placeholder="Enter API key" /></label><Button disabled={!key.trim()} onClick={() => void window.researchNotebook.settings.setOpenRouterKey({ key }).then(() => { setKey(''); setConfigured(true) }).catch(onError)}>Save key</Button></Modal> }
function JobsDialog({ onOpenChange, onError }: { onOpenChange: (open: boolean) => void; onError: (error: unknown) => void }): ReactElement { const [jobs, setJobs] = useState<Job[]>([]); const load = useCallback(async () => setJobs(await window.researchNotebook.jobs.list()), []); useEffect(() => { void load().catch(onError); const timer = window.setInterval(() => void load().catch(onError), 1200); return () => window.clearInterval(timer) }, [load, onError]); return <Modal title="Jobs" open onOpenChange={onOpenChange}><div className="jobs-list">{jobs.length ? jobs.map((job) => <div className="job-row" key={job.id}><div><strong>{job.kind}</strong><small>{job.status}{job.status === 'running' ? ` · ${job.progress}%` : ''}</small>{job.errorMessage && <small className="danger-text">{job.errorMessage}</small>}</div>{(job.status === 'queued' || job.status === 'running') && <Button variant="secondary" size="sm" onClick={() => void window.researchNotebook.jobs.cancel({ jobId: job.id }).then(load).catch(onError)}>Cancel</Button>}{(job.status === 'failed' || job.status === 'cancelled') && <Button variant="secondary" size="sm" onClick={() => void window.researchNotebook.jobs.retry({ jobId: job.id }).then(load).catch(onError)}>Retry</Button>}</div>) : <p className="dialog-copy">No background jobs.</p>}</div></Modal> }
function DiagnosticsDialog({ notebookId, onOpenChange, onError }: { notebookId: string | null; onOpenChange: (open: boolean) => void; onError: (error: unknown) => void }): ReactElement { const [result, setResult] = useState(''); return <Modal title="Diagnostics" open onOpenChange={onOpenChange}><p className="dialog-copy">Check asset integrity or export diagnostic information.</p>{result && <p className="diagnostic-result">{result}</p>}<div className="dialog-actions"><Button variant="secondary" disabled={!notebookId} onClick={() => void (async () => { if (!notebookId) return; const report = await window.researchNotebook.assets.diagnostics({ notebookId }); setResult(`${report.missing.length} missing · ${report.orphaned.length} unreferenced · ${report.untrackedFiles.length} untracked`) })().catch(onError)}>Scan assets</Button><Button variant="secondary" onClick={() => void window.researchNotebook.diagnostics.export().then((path) => setResult(path ? `Exported to ${path}` : 'No diagnostics to export.')).catch(onError)}>Export diagnostics</Button></div></Modal> }
function ExportDialog({ notebookId, workspace, activeNoteId, onOpenChange, onError }: { notebookId: string | null; workspace: PageWorkspace | null; activeNoteId: string | null; onOpenChange: (open: boolean) => void; onError: (error: unknown) => void }): ReactElement { const [scope, setScope] = useState<'notebook' | 'page' | 'note'>('page'); const start = async (format: 'markdown' | 'lossless-json' | 'ai-context' | 'pdf') => { if (!notebookId) return; try { await window.researchNotebook.exports.start({ scope: scope === 'note' && activeNoteId ? { type: 'note', noteId: activeNoteId } : scope === 'page' && workspace ? { type: 'page', pageId: workspace.id } : { type: 'notebook', notebookId }, format }); onOpenChange(false) } catch (error) { onError(error) } }; return <Modal title="Export" open onOpenChange={onOpenChange}><label className="field-label">Scope<select value={scope} onChange={(event) => setScope(event.target.value as typeof scope)}><option value="notebook">Notebook</option><option value="page" disabled={!workspace}>Current page</option><option value="note" disabled={!activeNoteId}>Active note</option></select></label><div className="export-options">{(['markdown', 'pdf', 'lossless-json', 'ai-context'] as const).map((format) => <Button key={format} variant="secondary" disabled={!notebookId} onClick={() => void start(format)}>{format.replace('-', ' ')}</Button>)}</div></Modal> }
function TrashDialog({ records, onOpenChange, onChanged, onError }: { records: TrashRecord[]; onOpenChange: (open: boolean) => void; onChanged: () => Promise<void>; onError: (error: unknown) => void }): ReactElement { return <Modal title="Trash" open onOpenChange={onOpenChange}><p className="dialog-copy">Restore items or permanently delete them.</p><div className="trash-list">{records.length ? records.map((record) => <div className="trash-row" key={`${record.entityType}-${record.id}`}><div><strong>{record.title}</strong><small>{record.entityType} · deleted {new Date(record.deletedAt).toLocaleDateString()}</small></div><Button variant="secondary" size="sm" onClick={() => void window.researchNotebook.trash.restore({ entityType: record.entityType, id: record.id, deletionOperationId: record.deletionOperationId }).then(onChanged).catch(onError)}>Restore</Button><Button variant="danger" size="sm" onClick={() => void window.researchNotebook.trash.permanentlyDelete({ entityType: record.entityType, id: record.id }).then(onChanged).catch(onError)}>Delete</Button></div>) : <p className="dialog-copy">Trash is empty.</p>}</div></Modal> }
function Empty({ onNewNotebook }: { onNewNotebook: () => Promise<void> }): ReactElement { return <div className="empty-state app-empty"><BookOpen size={34} /><h1>Your structured research workspace</h1><p>Create a notebook, then add pages, notes, and blocks.</p><Button onClick={() => void onNewNotebook()}>Create notebook</Button></div> }
